///* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
/* Header for class NdbEventStreaming */

#ifndef _Included_NdbEventStreaming
#define _Included_NdbEventStreaming
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NdbEventStreaming
 * Method:    startEventAPISession
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_hops_metadata_ndb_JniNdbEventStreaming_startEventAPISession(
		JNIEnv *, jobject, jstring, jstring jConnectionString,
        jstring jDatabaseName);

/*
 * Class:     NdbEventStreaming
 * Method:    closeEventAPISession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_hops_metadata_ndb_JniNdbEventStreaming_closeEventAPISession(
		JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
